### ISSUE TITLE
Not sure how to try the example

### ISSUE THREAD

**Issue by mellson** [Exact-Realty/lot#26]
I'm not sure how to test the example from the readme. When I install the package and try to use the example inside a React app I get this error:
```
export 'browserSandbox' (imported as 'browserSandbox') was not found in '@exact-realty/lot' (possible exports: default)
```

Do you have any tips on how to get the example running? Maybe an example app somewhere?

**Comment by mellson** [comment]
Update if I update the example slightly by removing the curly braces around the import something starts working:
```ts
// Notice that I removed the curly braces here {}
import browserSandbox from '@exact-realty/lot';

const sandbox = await browserSandbox(`
  /* sandboxed code*/;
  module.exports={hello:(name)=>\`Hello, ${name}!\`}; 
`);
const result = await sandbox('hello', 'World');
console.log(result); // Output: "Hello, World!"
```

**Comment by corrideat** [comment]
Thanks @mellson! I agree the example could be made better. Which runtime are you using?

Long story short, there are different exports for different environments. For example, if you run in Node and import the main module, you'll get this:

```
{
  bareSandbox: [Getter],
  browserSandbox: [Getter],
  freezePrototypes: [Getter],
  hardenGlobals: [Getter],
  nodejsSandbox: [Getter],
  workerSandbox: [Getter]
}
```

However, there are more specialised exports included for different runtimes, or to use for bundling. If you're running outside of Node.js, the `package.json` gives you the 'right' export for that environment, which you can override by importing a specialised import (e.g., `@exact-realty/lot/browser`).

So, back to your question, your change is correct when using it in non-Node runtimes. I'm going to assume Deno here, and what you get is the same as the `workerSandbox` (or `@exact-realty/lot/worker`), which is the runtime supported by Deno.

Some variations:

  * `@exact-realty/lot/bare`: _Experimental export that probably you don't want to use in most cases._ It relies solely on JS-level isolation. No `iframe`, no `Worker`, no `node:vm`, etc. Using this requires somewhat securely also requires modifying some of the globals in the host environment (for example, to block `Function`, `eval`, etc.). This should work in most/all modern JS environments. This is also the core functionality that powers the rest of the isolation strategies.
  * `@exact-realty/lot/browser`: Browser module with sandbox in an iframed `Worker`, with fallback to just an iframe. This is most compatible but has larger bundle size, and the fallback mechanism makes it less isolated.
  * `@exact-realty/lot/browser-window`: Browser module with sandbox in an iframe, without using a Worker at all. This might work in some cases, but is not as isolated as an iframed Worker.
  * `@exact-realty/lot/browser-worker`: Browser module with sandbox in an iframed `Worker` with no fallback.
  * `@exact-realty/lot/nodejs`: Export for Node.js-only. It uses worker threads and the vm module for isolation.
  * `@exact-realty/lot/worker`: Module with a sandbox in a `Worker`. This module will also work in a browser, but it doesn't use an `iframe` at all, so it's less isolated that the other browser-specific modules. This is the default export for Deno, and the only one that Deno supports.

**Comment by mellson** [comment]
Nice, thank you 👍🏻 That makes sense. I'm testing this for use in the browser, so I will try to import from `@exact-realty/lot/browser`
